// file: HotelmaniaOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package es.upm.fi.emse.hotelmania;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: HotelmaniaOntology.java
 * @author ontology bean generator
 * @version 2015/04/24, 17:49:57
 */
public class HotelmaniaOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "Hotelmania";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new HotelmaniaOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String HOTELREGISTRATION_HOTEL="hotel";
    public static final String HOTELREGISTRATION="HotelRegistration";
    public static final String HOTEL_HOTELID="hotelId";
    public static final String HOTEL="Hotel";

  /**
   * Constructor
  */
  private HotelmaniaOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema hotelSchema = new ConceptSchema(HOTEL);
    add(hotelSchema, es.upm.fi.emse.hotelmania.Hotel.class);

    // adding AgentAction(s)
    AgentActionSchema hotelRegistrationSchema = new AgentActionSchema(HOTELREGISTRATION);
    add(hotelRegistrationSchema, es.upm.fi.emse.hotelmania.HotelRegistration.class);

    // adding AID(s)

    // adding Predicate(s)


    // adding fields
    hotelSchema.add(HOTEL_HOTELID, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    hotelRegistrationSchema.add(HOTELREGISTRATION_HOTEL, hotelSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
